# Extra autostart processes
exec-once = python3 ~/.config/hypr/scripts/zen_workspace_assigner.py
exec-once = ~/.config/hypr/scripts/start-online-apps.sh
exec-once = spotify
exec-once = uwsm-app -- xdg-terminal-exec --dir="$HOME"
