# Window rules
# See:
# https://wiki.hypr.land/Configuring/Window-Rules/
# https://wiki.hypr.land/Configuring/Workspace-Rules/

# Workspace-to-monitor mapping
workspace = 1, monitor:DP-1, default:true, persistent:true
workspace = 5, monitor:DP-1, persistent:true

workspace = 2, monitor:DP-2, default:true, persistent:true
workspace = 4, monitor:DP-2, persistent:true
workspace = 7, monitor:DP-2, persistent:true
workspace = 8, monitor:DP-2, persistent:true
workspace = 9, monitor:DP-2, persistent:true

workspace = 3, monitor:DP-3, default:true, persistent:true
workspace = 6, monitor:DP-3, persistent:true
workspace = 10, monitor:DP-3, persistent:true

# App placement
windowrule = workspace 1, match:class chrome-web\.akiflow\.com__-Default
windowrule = workspace 3, match:class chrome-www\.facebook\.com__messages_e2ee_t-Default
windowrule = workspace 10, match:class chrome-app\.shortwave\.com__-Default
windowrule = workspace 3, match:class chrome-discord\.com__channels_@me-Default
windowrule = workspace 3, match:class slack

windowrule = workspace 4, match:class (Alacritty|kitty|com\.mitchellh\.ghostty)
windowrule = workspace 2, match:class zen
windowrule = workspace 6, match:class Spotify
windowrule = workspace 7, match:class obsidian
windowrule = workspace 8, match:class steam

# Keep Steam games on the center gaming workspace.
windowrule = tile on, match:class steam_app.*
windowrule = monitor DP-2, match:class steam_app.*
windowrule = workspace 8, match:class steam_app.*
windowrule = fullscreen on, match:class steam_app.*
